# Generated by Django 3.0.8 on 2020-07-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clubs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClubName', models.CharField(max_length=200)),
                ('ClubID', models.IntegerField()),
                ('Group', models.CharField(max_length=200)),
                ('Sponsoring', models.CharField(max_length=200)),
                ('President_Name', models.CharField(max_length=200)),
                ('President_Mail', models.EmailField(max_length=254)),
                ('Secretary_Name', models.CharField(max_length=200)),
                ('Secretary_Mail', models.EmailField(max_length=254)),
                ('Username', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=32)),
                ('Sponsoring_Mail', models.EmailField(max_length=254)),
                ('Group_Mail', models.EmailField(max_length=254)),
                ('District_Mail', models.EmailField(max_length=254)),
                ('Registered_Date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
