# Generated by Django 3.0.8 on 2020-07-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubadmin', '0002_auto_20200721_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='Avenue',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='ProjectTitle',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='Venue',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
