# Generated by Django 3.0.8 on 2020-07-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubadmin', '0003_auto_20200721_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='Status',
            field=models.CharField(default='active', max_length=10),
        ),
    ]
