# Generated by Django 3.0.8 on 2020-07-22 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubadmin', '0004_projects_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('ReportId', models.AutoField(primary_key=True, serialize=False)),
                ('ProjectTitle', models.CharField(max_length=200, null=True)),
                ('NoofClubMembers', models.CharField(max_length=200, null=True)),
                ('NoofOtherClubMembers', models.CharField(max_length=200, null=True)),
                ('NoofCouncilMembers', models.CharField(max_length=200, null=True)),
                ('Duration', models.CharField(max_length=200, null=True)),
                ('ProjectDescription', models.CharField(max_length=200, null=True)),
                ('ReportPic', models.ImageField(blank=True, null=True, upload_to='')),
                ('ProjectId', models.ForeignKey(max_length=32, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clubadmin.Projects')),
            ],
        ),
    ]
